### ISSUE TITLE
`dwarffs` fails to build against latest `nix-2.19.2` release

### ISSUE THREAD

**Issue by trofi** [edolstra/dwarffs#26]
The build fails as:

```
g++ -c -g -std=c++17 -Wall -Os dwarffs.cc -o dwarffs.o
dwarffs.cc:10:10: fatal error: fs-accessor.hh: No such file or directory
   10 | #include "fs-accessor.hh"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

Possibly caused by https://github.com/NixOS/nix/commit/1a902f5fa7d4f268d0fec3e44a48ecc2445b3b6b

**Comment by trofi** [comment]
https://github.com/edolstra/dwarffs/pull/30 fixed the build against the latest `nix` for me.
